### ISSUE TITLE
Não consigo Instalar no meu Sistema o Jshell REPL

### ISSUE THREAD

**Issue by miscapu** [PikaTimer/PikaTimer#20]
Senhores gostaria de saber como consigo instalar o Jshell REPL do Java no meu sistema...estou com o jdk8 version 171...já tentei colocar o caminho nas variáveis de ambiente mas não consigo.

**Comment by segfaultcoredump** [comment]
> I would like to know how I can install the Java REPL JShell on my system ... I have jdk8 version 171 ... I already tried to put the path in the environment variables but I can not do it.

This forum is for issues with PikaTimer. General JDK Jshell installation issues should be directed to Oracle or the OpenJDK community.
