### ISSUE TITLE
Date of Birth order

### ISSUE THREAD

**Issue by bighillevents** [PikaTimer/PikaTimer#27]
Hi, I've been looking at using your software for a running event I have here in Australia.
I am playing with the setup but when I put in my participant import the date of birth loads only as US style.
when we collect dates of birth here in Australia we collect Day / Month / Year.

Is this something that you think could be overcome?

Also slightly different, my event has some pretty unique categories (I think you use the term awards)
I did not see any import option for identifying an award in the import.  It seems awards only relates to age ranges.  So in my case I assume just go and set up each of my categories as a Race in your system?

Thanks in Advance.
rohin

**Comment by segfaultcoredump** [comment]
Date parsing is one of the banes of my existence. :-) 

The code in question can be seen at (https://github.com/PikaTimer/pikatimer/blob/master/src/com/pikatimer/participant/Participant.java#L492)  
When importing a date of birth, it attempts to parse them in this order:

- ISO_LOCAL_DATE format: YYYY-MM-DD
- US Style: M/d/yyyy
- "Local" : <varies depending on the local> 

If I swap the 2nd and 3rd options it should take care of it for all of us.  I'll add that to the next release. 


In terms of the categories (aka awards), the latest (v1.5.1) version has a dramatically improved set of options, so use that first. It defaults to setting the usual overall/masters/age-group. But you can delete all of those and setup your own based on totally arbitrary rules. 

Look at section 4.2.3 in the user manual at https://github.com/PikaTimer/pikatimer/releases/download/v1.5.1/PikaTimer.1.5.User.Manual.pdf  for the full details. 

Note that if you define custom attributes for your participants you can also key off of those in your custom categories. For example, if you are have an event that has a big fund raiser component, you can define a custom attribute for the participants called "donation amount" and then setup an award called "Big Donors" that only applies to participants who donated more than $100 (AUD of course) by setting up a filter on that attribute. 

--john

**Comment by segfaultcoredump** [comment]
Take a look at the 1.5.2 release at https://github.com/PikaTimer/pikatimer/releases/tag/v1.5.2 to see if it fixes the issue.

**Comment by segfaultcoredump** [comment]
Given that this has not had a comment in 3 years and appears to be fixed, I'm closing this issue.
