### ISSUE TITLE
Overall (Responsive HTML) result does not have any data

### ISSUE THREAD

**Issue by anca-racehub** [PikaTimer/PikaTimer#31]
After processing a result of Overall (Responsive HTML) the file contains no results.

Below is a screenshot with all options.
![screenshot_11](https://user-images.githubusercontent.com/10059493/52061601-5b9f1900-2577-11e9-999f-9a478ad7c029.png)

The HTML file has a header but no data.
![screenshot_12](https://user-images.githubusercontent.com/10059493/52061712-a0c34b00-2577-11e9-9bd8-3bce5bee64da.png)

Changing to Overall CSV or text works fine

**Comment by segfaultcoredump** [comment]
The "Loading..." tells me that the system had an issue parsing the embedded json output. This text is removed once the system has loaded the results. 

See https://pikespeakmarathon.org/results/ppm/2018/ for an example of the behavior. 

If you don't mind, can you attach either the resulting html file or provide a link to the file so I can view it in an attempt to determine what caused the issue?

Thanks,

--john

**Comment by anca-racehub** [comment]
I have attached the file (please rename it .html)

[2349-responsive.log](https://github.com/PikaTimer/pikatimer/files/2835360/2349-responsive.log)
it seems there is a JS error in console.

Let me know if you need anything else.

**Comment by segfaultcoredump** [comment]
Thanks for the sample file, it pointed me to the error.

The custom attribute name was being used as an identifier, and you can't have spaces or other reserved items in identifiers. So I escape the text to produce something that is safe for use as an identifier. 

The change can be viewed at https://github.com/segfaultcoredump/pikatimer/commit/f1435fb3ce9dfd8474927b2feaae7f1beebed5fb

**Comment by segfaultcoredump** [comment]
Take a look at the 1.5.2 release at https://github.com/PikaTimer/pikatimer/releases/tag/v1.5.2 to see if it fixes the issue.

**Comment by anca-racehub** [comment]
It works now. Thanks
