### ISSUE TITLE
Results from Specific Award have titles mixed text and code

### ISSUE THREAD

**Issue by anca-racehub** [PikaTimer/PikaTimer#32]
I have configured a custom award a result that uses the custom award.
The titles of the awards are mixed. 
Example:
ClasamentCategorii StringProperty [value: Feminin 19-35 ani]
it should be
ClasamentCategorii  Feminin 19-35 ani
without StringProperty and value.

Below is custom award configuration
![screenshot_14](https://user-images.githubusercontent.com/10059493/52062156-a53c3380-2578-11e9-936a-747296164fb3.png)

In the results page the configuration of the result
![Uploading Screenshot_13.png…]()

The text file exported contains the below text:

                             SKV Uphill Winter 2019                             
                                Alergare montana                                
                                January 26, 2019                                

                                  ***Awards***                                  

  ********ClasamentCategorii StringProperty [value: Feminin 19-35 ani]********  
Place Name            BIB AGE SEX AG    City                Club        Age group              Time
  1   stela ratiu      34  32  F  19-35                                Feminin 19-35 ani   1:01:21

 ********ClasamentCategorii StringProperty [value: Masculin 19-35 ani]********  
Place Name            BIB AGE SEX AG    City                Club        Age group              Time
  1   Paul Sovaila     23  29  M  19-35                                Masculin 19-35 ani  1:02:21

**Comment by segfaultcoredump** [comment]
Thanks for spotting this.

I think I found the issue:

At https://github.com/PikaTimer/pikatimer/blob/master/src/com/pikatimer/race/AwardCategory.java#L628 this line:
`try {splitCat += r.getCustomAttribute(Integer.parseInt(attrib)) + " ";} catch (Exception e){}`
should read
`try {splitCat += r.getCustomAttribute(Integer.parseInt(attrib)).getValueSafe() + " ";} catch (Exception e){}`

I should have this fixed in the next release.

--john

**Comment by segfaultcoredump** [comment]
Take a look at the 1.5.2 release at https://github.com/PikaTimer/pikatimer/releases/tag/v1.5.2 to see if it fixes the issue.

**Comment by anca-racehub** [comment]
Looks fixed. Thanks
