### ISSUE TITLE
Result Overall (JSON) improvment for custom awards

### ISSUE THREAD

**Issue by anca-racehub** [PikaTimer/PikaTimer#33]
It would be very useful (for those that are automatically processing results with a script)
to have the JSON response improved for custom awards

Example:

Configuration screenshot
==========
![screenshot_15](https://user-images.githubusercontent.com/10059493/52108680-6901e500-2603-11e9-8e84-b2eaa9533e02.png)
Result
	{
		"bib": "34",
		"age": "30",
		"sex": "F",
		"ag": "0+",
		"full_name": "stela cotonea",
		"full_name_filter": "stela cotonea",
		"first_name": "stela",
		"middle_name": "",
		"last_name": "cotonea",
		"city": "",
		"state": "",
		"country": "",
		"note": "",
		"custom_Age group": "Feminin 19-35 ani",
		"award_winner": "yes",
		"awards": {
			"award_0": "1st Overall &mdash; Female (Time: 1:01:21)",
			"award_1": "1st ClasamentCategorii &mdash; StringProperty [value: Feminin 19-35 ani] (Time: 1:01:21)"
		},
		"oa_place": "1",
		"sex_place": "1",
		"ag_place": "1",
		"last_seen": "Never",
		"start_display": "16:00:00",
		"finish_display": "1:01:21",
		"finish_sort": "1:01:21",
		"finish_pace": "6:08/km"
	},

Desired behavior:

the awards object could have the fields split like below:

"awards": {
			"award_0":  {
						"title": "1st Overall Female (Time: 1:01:21)",
						"place":"1",
						"time":"1:01:21"
			},
			"award_1":  {
						"title": "1st ClasamentCategorii - Feminin 19-35 ani (Time: 1:01:21)",
						"place":"1",
						"time":"1:01:21"
			}
		},
This way it could be easily parsed by a script.

**Comment by segfaultcoredump** [comment]
I don't want to break the existing use of the awards array, so how about something like this?

```
		"award_winner": "yes",
		"awards": {
			"award_0": "1st Overall - Male (Time: 3:32:20)"
		},
		"award_Detail": {
			"award_Overall": {
				"title": "Overall",
				"category": "Male",
				"place": "1",
				"time": "3:32:20",
			}
		}
```

**Comment by anca-racehub** [comment]
That's perfect. When are you planning the next release? or beta version?

**Comment by segfaultcoredump** [comment]
Take a look at the 1.5.2 release at https://github.com/PikaTimer/pikatimer/releases/tag/v1.5.2 to see if it fixes the issue.

**Comment by anca-racehub** [comment]
Thanks for the fix, it works now.
