### ISSUE TITLE
Setup minimum time from preivous split for finish line

### ISSUE THREAD

**Issue by anca-racehub** [PikaTimer/PikaTimer#37]
We need to be able to setup the minimum time from previous lap also for the finish line.
Consider the following setup: 1 race with 4 laps, the average lap time is about 4 minutes.
I can configure the minimum time for split 1, split 2 and split 3. But I cannot configure the minimum time between split 3 and finish. This time is by default 5 minutes (as we discovered)

Is there any way to change this default setting without a release? We need this setup for May 18th and we cannot time it because we cannot change that value.
Can you please help? Any workaround is welcomed.

**Comment by segfaultcoredump** [comment]
Try this:
Grab a copy of PikaTimer version 1.5 from https://github.com/PikaTimer/pikatimer/releases/tag/v1.5 and use that to create the race and setup the splits. It was the last release that treated the start and finish splits like any other split. I believe that it provides the option to set the min time from the previous split there. You may need to uninstall the existing version or use a 2nd computer with the older version on it to create the pika timer race file and then copy it to your timing computer. 

Then use the most recent version (1.5.2) to open the race created in version 1.5 do the actual race day timing. The option to edit the minimum time is no longer visible, but it is still there in the database and the system will honor it.

For version 1.6, I'll try and figure out a way to make it editable again for cases like this.

**Comment by redbarron1994** [comment]
Is there any update on its way to allow timers to adjust the minimum time between the final split?

**Comment by segfaultcoredump** [comment]
After a (very) long delay, v [1.6 Beta 1 ](https://github.com/PikaTimer/pikatimer/releases/tag/v1.6beta1) is now available.  

On the main "Event Details" tab, there is a + sign next to the Finish Location. You can then specify the minimum time from the last split (which is the start line in a race with no on-course splits. )  

I still need to update the documentation, but at least the app is out there.
