### ISSUE TITLE
Problem starting my terminal in highSierra 10.12.6

### ISSUE THREAD

**Issue by miscapu** [PikaTimer/PikaTimer#38]
I'm starting my terminal on a Mac HighSierra 10.12.6 and this is what it shows me:
`Restored session: Dom 21 Mar 2021 12:19:28 -03
-bash: /usr/local/opt/php@7.2/sbin:/usr/local/opt/php@7.2/bin:/usr/local/mysql/bin:/usr/local/mysql/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/mysql/bin:/usr/local/mysql/bin: No such file or directory`

![Cloth capture](https://user-images.githubusercontent.com/25410070/111910756-72e43d80-8a41-11eb-8c49-10364511a624.png)

All of this happened after installing the HomeBrew.
I already tried to uninstall Homebrew and failed to fix the problem.

My / usr / local folder is as in the image:
![Cloth capture](https://user-images.githubusercontent.com/25410070/111910797-96a78380-8a41-11eb-9923-4a66eb95ce3b.png)

**Comment by segfaultcoredump** [comment]
I'm closing this issue since the problem described has no apparent relation to the PikaTimer application.
