### ISSUE TITLE
How to use pikatimer

### ISSUE THREAD

**Issue by LWMcQ** [PikaTimer/pikatimer#41]
I have downloaded pikatimer, but have no idea how to use it. That is to say, I don't know where to begin to run it. I have never used a java program before and don't know how to get it started. I'm on Windows 10 X 64 Thanks.

**Comment by KoosPiet** [comment]
Hi, On the main page there is a very extensive user manual that will get you on the way and help you out

**Comment by KoosPiet** [comment]
there is also a windows install file that will install it all for you

**Comment by LWMcQ** [comment]
I'm not sure how I missed both the install download and the manual, but I
did

Thank you for your response,

Dave

**Comment by segfaultcoredump** [comment]
Cleaning up the old issue since it appears resolved.
