### ISSUE TITLE
Arduino RFID Reader

### ISSUE THREAD

**Issue by KoosPiet** [PikaTimer/pikatimer#42]
thanks for an amazing program! I would like to know however if it is possible to use a Arduino/Raspi to do the RFID scanning? We have a very small club in South Africa and those RFID scanners are very expensive so we are trying to find an alternative method.

**Comment by segfaultcoredump** [comment]
That would be a bit out of scope for this app at this time. 

It is possible to write an app that runs on top of an Arduino / Raspberry Pi that then communicates with the RFID hardware. See [https://pimylifeup.com/raspberry-pi-rfid-rc522/](https://pimylifeup.com/raspberry-pi-rfid-rc522/) for an example 

After that, the trick is how to feed it to PikaTimer. Whoever writes the app on the embedded controller would then need to create an API that PikaTimer can consume. 

The app currently has support for direct connections to the [RFID Timing](https://rfidtiming.com/) hardware which uses a similar microcontroller setup.   You can see the code for that integration at [https://github.com/PikaTimer/pikatimer/blob/master/src/com/pikatimer/timing/reader/PikaRFIDDirectReader.java](https://github.com/PikaTimer/pikatimer/blob/master/src/com/pikatimer/timing/reader/PikaRFIDDirectReader.java) to get started.
